### ISSUE TITLE
Funding app for GoL

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#230]
### User Story

As a validator, I would love to have a joyful app for contribution during Game of Links.

### Solution

Mockup:
![2019-08-28 15 17 14](https://user-images.githubusercontent.com/410789/63859206-2ccf1100-c9a7-11e9-96ab-2e3f6d819950.jpg)

Params of application:
- funding address
- number of block start
- common incentive curve (2 polynoms)
- personal discount function (step and %)
- the goal in ATOMs
- Amount to distribute

Indicators:
- ATOMs left (in the center) (?) => explain different round logic
- Current discount
- Cyb won (?) => explain key game principle

Chart:
- (example)[https://github.com/cybercongress/congress/pull/229#issuecomment-525388516]
- as input table with 600 dots on 3 axis

Popup content on chart dot:
- 3% or 30 TCYB allocated
- 300000 ATOMs contributed
- 15% personal discount

Show all contributions in the table. If the current address has contributions show them in an additional table.

Fields of tx tables (recent first):
- Timestamp (human understandable)
- TxId (bigdeeper link)
- ATOMs contributed 
- GCYB estimation (?) => Amount of allocated GCYB depend on the total amount contributed and personal discount. So two rules are applied: (1) The more ATOMs contributed, the higher the price the less GCYB is allocated for your contribution. (2) The earlier your contribution is done the bigger price discount you have. In this table is being displayed estimation based on known amount of contributions.
- Price estimation (?) => The same.

Action bar:
- Contribute ATOMs using {any cosmos wallet} => [Fuck Google] => You can send any amount of ATOMs to cyber•Congress multisig cosmos287fhhlgflsef [Track Contribution] Put address of wrom which you contributed {input for address} [Save address]
- You can contribute ATOMs using {ledger} => [Fuck Google] => I want contribute {input} ATOMs [Confirm] => Transaction cost is 0.1 uATOM [Sign] => Tx id succesfuuly confirmed (link to bigdeeper) timeout 10 second => Standart state

App has 3 states:
- before funding block => countdown and Fuckgoogle button is not active
- during funding = > as described
- after reaching the goal in ATOMs => Final Price, Atoms left => Funded.
Game of links round has been ended in [amount of day/hours/minutes] 

### Definition of Done
The app is fully functional under https://cybercongress.ai main page, connected to cosmos-hub-3 and is capable to monitor transactions in realtime and sign transactions with ledger

**Comment by mrlp4** [comment]
Update GOL status page.

- [ ] 1. ATOMS left to fund - calculate sum of all transactions to multisig, 600k  minus all sum.
- [ ] 2. add battery style to graph - bold green line
- [x] 3. make graph larger
- [x] 4. remove price history
- [x] 5. put Game of Links to title, Game of links ended when done
- [x] 6. change grid color to gray 
- [x] 7. make all zeros to one place 
- [ ] 8. popup on graph back with green frame and green font
- [x] 9. remove controls from graph. leave 2 or 3 fixed views in 2d
- [x] 10. make static graph, not moving

**Comment by SaveTheAles** [comment]
> 1. ATOMS left to fund - calculate sum of all transactions to multisig, 600k minus all sum.

it is not correct as @xhipster mentioned before 
we need to accumulate income txs and count by them

**Comment by mastercyb** [comment]
1. Сделать батарейку и счетчик общим для страниц приложения
2. Кликабельные сектора батарейки
3. Коммуникация внтури ишью
4. Коммуникация через хеш приложения для фидбека
5. Единая компоновка страниц

**Comment by dimakorzhovnik** [comment]
QmUSVm25Xy2kZ3ZtEd87VTjLbB2bAMq9FHHUevcrcdJZy7
