### ISSUE TITLE
Launch Game of Links

### ISSUE THREAD

**Issue by SaveTheAles** [cybercongress/congress#232]
- [x] [Euler-5 release](https://github.com/cybercongress/cyberd/projects/3)
- [x] [Episode-1 release](https://github.com/cybercongress/dot-cyber/projects/2)
- [x] [0.1.0 launch-kit](https://github.com/cybercongress/launch-kit/projects/1)
- [x] [Rules](https://github.com/cybercongress/congress/blob/31688cb04805e31a13392b94a62617a5c811a15a/blog/releases/gol-rules/game-of-links.md)
