### ISSUE TITLE
Open Bootstrap Evangelism Program

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#307]
Some work [already done](https://github.com/cybercongress/congress/tree/master/ecosystem/donations). Lets discuss full deliverables

**Comment by serejandmyself** [comment]
I think before launch of the program we need to:

- [ ] Clean congress repo (readme/folders) (there is a starting PR submitted already)
- [ ] Discuss possible extras: [cosmostation](https://github.com/cybercongress/congress/issues/304), CMC, media mentions, [stakingrewards](https://www.stakingrewards.com/) listing, letters to [projects investing into Cosmos](https://forum.cosmos.network/t/funding-your-cosmos-tendermint-startup/809/10) (done)
- [ ] Ongoing work with community, posts, ecosystem - done

Please let me know, what is relevant 

Other things to complete for the program:

- [ ] Lists of youtubers, bloggers, etc, that we wish to offer the program to
- [ ] Lists of other services/people that we wish to offer participation to

**Comment by serejandmyself** [comment]
**Open Bootstrap Evangelism Program (OBEP): program breakdown**

- _Mission:_ Increase initial traction. Build strong local and /or online community
- _Tooling:_ cyber tools that help. Creativity
- _Total pot_ : Community pool (2 TCYB). Small liquid payments + 10% from donations in ATOM(!) for each tx
- _Roles:_ Evangelist/Ambassador. Translator
- _General Tasks:_ Game of Links. Game of Thrones. Be part of the project. Open evangelism program. Translations.
- _Incentives in numbers:_ 
    - Translations - 20 GCYB
    - Ambassador/Evangelist -  80 GCYB
    - Evangelist/Translator coordinator - 120 GCYB
- _Translator:_ Translate WP, twitter or any other linguistic creativity
- _Amabassador/Evangelist:_ Donations, helping local / online community, creates and runs chats, preferably speaks a language for quality control. Accepted after an interview from coordinator 
- _Timeframe:_ From when launched officially to when stopped manually (launch of mainet). Ambassadors still remain. Governance decides on new community pool  (will probably decrease in proportion)

**Comment by xhipster** [comment]
Lets discuss the size of bag for Evangelists.

**Comment by xhipster** [comment]
Bump

**Comment by serejandmyself** [comment]
Based on my presumption of 4 evangelists + 8 translators (some might cross):
- 20*8 = 160 (8 translations)|
- 0.1*20=2 (20 retweets of translations)
- 1.5*4 = 6 (4 local communities created)
- 2.5*8 = 20 (8 online events, 2 per evangelist)
- 0.5*10=5 (10 meaningful blog posts created)
- 20*4 = 80 (4 meetups, one per evangelist)
- 10*24 = 240 (Out of the assumption that evangelists + other participants of referees can bring 20% donations. For each 5K ATOM - 10 GCYB)
- 120 (coordination)
Total pot for evangelists: 633 GCYB
Based on 25% of giving a wrong answer, that would make it between: 475 - 800 GCYB

**Comment by serejandmyself** [comment]
**Open Bootstrap Evangelism Program (OBEP): program breakdown**
**V2**

UPDATE PROPOSITION 

- _Mission:_ Increase initial traction. Build strong local and/or online community
- _Tooling:_ cyber.page
- _Total pot_ : Community pool: 0.8 TCYB + 10% from donations in ATOM for each tx
- _Roles:_ Evangelist. Translator
- _General Tasks:_  Populirize takeoff, Game of Links & Game of Thrones. Be part of the project. Open evangelism program. Translations.
- _Incentives in numbers:_ 

|METRIC  | REWARD | COMMENT |
|:----------|:-------------:|------:|
| Translation | 20 GCYB | Any language! |
| Community creation | 1.5 GCYB | For 1 local channel on TG/Riot/Matrix/Keybase with over 50 people and 300 total meaningful messages - one person can only create 1 community |
| Online video/podcast |  2.5 GCYB | Events should be marketed to the broader community - proof required |
| Blog post | 1 GCYB | 1500+ words, original writing. Should be marketed to the broader community |
| DR (donation relations) | 5 GCYB  | for each 1k ATOM from one address | 
| Meetup | 20 GCYB | For each meetup with over 10 people - photo proof + a recording are required + at least 12 attendees. Limited to one meaningful meetup for the period of GoL |
| Coordinator | 30 - 120 GCYB | 30 GCYB for overseeing OBEP + 30 GCYB for each onboarded evangelist thereafter. But - 120 max |

    - Evangelist/Translator coordinator - The coordinator is responsible for checking local channels, quality of work, onboarding of OBEP, checking proofs and metrics
    - 10% from each tx in ATOM during donations for accepted to OBEP

- _Translator:_ Translate WP + share their work on twitter or any other channels
- _Evangelist:_ Donations, helping build local/online communities, creates and runs chats, preferably speaks a language for quality control. Accepted after an interview from the coordinator 
- _Timeframe:_ From when launched officially to when either pool runs out or end of GoL or stopped manually (launch of mainnet). 
- _Afterlife:_ Governance decides on evangelists new community pool  (will probably decrease in proportion)
- **To receive reward:** 
1) Anything must be cyberlinked! 
2) Blog posts, videos, meetups, etc are subject to manual check. The evangelist will get rewrded if he did the job, but if its not accepted due to lack of quality or an attempt to cheat, he will not be able to carry on the program

**Comment by serejandmyself** [comment]
https://github.com/cybercongress/congress/blob/master/ecosystem/donations/obep.md

**Comment by serejandmyself** [comment]
cyber.page/evangelism
