### ISSUE TITLE
Cleanup docs

### ISSUE THREAD

**Issue by xhipster** [cybercongress/congress#34]
- [x] Move knowledge repo to congress
- [x] Kill all wikis
- [x] Move all documentation to `/docs` folders
- [x] Restructure documentation according to projects
- [x] Communicate with the team about critical missing stuff
- [x] Script collecting docs from project `/docs` folder

**Comment by cyberadmin** [comment]
missing links in cyber.search
